// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKjbFB_7YwjslCAABm2fGBf38d_mbG3i4',
    appId: '1:25317862758:web:a209c045ee1a47d8d6eca7',
    messagingSenderId: '25317862758',
    projectId: 'campus360-2025',
    authDomain: 'campus360-2025.firebaseapp.com',
    storageBucket: 'campus360-2025.firebasestorage.app',
    measurementId: 'G-KK74STW0Q1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV92doarDZuOAY-OESypJJKQaOb60Rnko',
    appId: '1:25317862758:android:24c84a7590f2bb2ad6eca7',
    messagingSenderId: '25317862758',
    projectId: 'campus360-2025',
    storageBucket: 'campus360-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD8pXfO11nRFfpxb8TtemA3bcYRINg2r0',
    appId: '1:25317862758:ios:b14a308b66123c29d6eca7',
    messagingSenderId: '25317862758',
    projectId: 'campus360-2025',
    storageBucket: 'campus360-2025.firebasestorage.app',
    iosBundleId: 'com.example.repositoryCampus360',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAD8pXfO11nRFfpxb8TtemA3bcYRINg2r0',
    appId: '1:25317862758:ios:b14a308b66123c29d6eca7',
    messagingSenderId: '25317862758',
    projectId: 'campus360-2025',
    storageBucket: 'campus360-2025.firebasestorage.app',
    iosBundleId: 'com.example.repositoryCampus360',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKjbFB_7YwjslCAABm2fGBf38d_mbG3i4',
    appId: '1:25317862758:web:e7f600c163444d99d6eca7',
    messagingSenderId: '25317862758',
    projectId: 'campus360-2025',
    authDomain: 'campus360-2025.firebaseapp.com',
    storageBucket: 'campus360-2025.firebasestorage.app',
    measurementId: 'G-KYSCXKBG1Z',
  );
}
