// lib/utils/firebase_seed.dart
import 'package:cloud_firestore/cloud_firestore.dart';

Future<void> seedSpacesData() async {
  final firestore = FirebaseFirestore.instance;

  // 추가할 데이터 목록
  final spacesData = [
    // ========== 1기술관 - 2층 ==========
    {
      "name": "CAD실습실",
      "location": "1기술관 2층",
      "capacity": 30,
      "image": "",
      "mainImageUrl": "",
      "view360Url": "",
      "facilities": ["Wi-Fi", "스크린", "에어컨", "콘센트"],
      "description": "CAD 실습 전용 강의실",
      "building": "1기술관",
      "floor": "2층",
      "createdAt": FieldValue.serverTimestamp(),
    },
    {
      "name": "콘트롤러실습실",
      "location": "1기술관 2층",
      "capacity": 30,
      "image": "",
      "mainImageUrl": "",
      "view360Url": "",
      "facilities": ["Wi-Fi", "스크린", "에어컨", "콘센트"],
      "description": "콘트롤러 실습 전용 강의실",
      "building": "1기술관",
      "floor": "2층",
      "createdAt": FieldValue.serverTimestamp(),
    },

    // ========== 2기술관 - 1층 ==========
    {
      "name": "CATIA실습실",
      "location": "2기술관 1층",
      "capacity": 30,
      "image": "",
      "mainImageUrl": "",
      "view360Url": "",
      "facilities": ["Wi-Fi", "스크린", "에어컨", "콘센트"],
      "description": "CATIA 실습 전용 강의실",
      "building": "2기술관",
      "floor": "1층",
      "createdAt": FieldValue.serverTimestamp(),
    },
    {
      "name": "전기자동차실습실",
      "location": "2기술관 1층",
      "capacity": 30,
      "image": "",
      "mainImageUrl": "",
      "view360Url": "",
      "facilities": ["Wi-Fi", "스크린", "에어컨", "콘센트"],
      "description": "전기자동차 실습 전용 강의실",
      "building": "2기술관",
      "floor": "1층",
      "createdAt": FieldValue.serverTimestamp(),
    },
    {
      "name": "자동차과이론강의실",
      "location": "2기술관 1층",
      "capacity": 40,
      "image": "",
      "mainImageUrl": "",
      "view360Url": "",
      "facilities": ["Wi-Fi", "스크린", "에어컨"],
      "description": "자동차과 이론 강의실",
      "building": "2기술관",
      "floor": "1층",
      "createdAt": FieldValue.serverTimestamp(),
    },

    // ========== 2기술관 - 2층 ==========
    {
      "name": "자동차과이론강의실",
      "location": "2기술관 2층",
      "capacity": 40,
      "image": "",
      "mainImageUrl": "",
      "view360Url": "",
      "facilities": ["Wi-Fi", "스크린", "에어컨"],
      "description": "자동차과 이론 강의실",
      "building": "2기술관",
      "floor": "2층",
      "createdAt": FieldValue.serverTimestamp(),
    },
    {
      "name": "CAD/CAE실",
      "location": "2기술관 2층",
      "capacity": 30,
      "image": "",
      "mainImageUrl": "",
      "view360Url": "",
      "facilities": ["Wi-Fi", "스크린", "에어컨", "콘센트"],
      "description": "CAD/CAE 실습 전용 강의실",
      "building": "2기술관",
      "floor": "2층",
      "createdAt": FieldValue.serverTimestamp(),
    },

    // ========== 2기술관 - 3층 ==========
    {
      "name": "자동차과이론강의실",
      "location": "2기술관 3층",
      "capacity": 40,
      "image": "",
      "mainImageUrl": "",
      "view360Url": "",
      "facilities": ["Wi-Fi", "스크린", "에어컨"],
      "description": "자동차과 이론 강의실",
      "building": "2기술관",
      "floor": "3층",
      "createdAt": FieldValue.serverTimestamp(),
    },
    {
      "name": "PLC실습실",
      "location": "2기술관 3층",
      "capacity": 30,
      "image": "",
      "mainImageUrl": "",
      "view360Url": "",
      "facilities": ["Wi-Fi", "스크린", "에어컨", "콘센트"],
      "description": "PLC 실습 전용 강의실",
      "building": "2기술관",
      "floor": "3층",
      "createdAt": FieldValue.serverTimestamp(),
    },

    // ========== 3기술관 - 1층 ==========
    {
      "name": "아이디어 존",
      "location": "3기술관 1층",
      "capacity": 20,
      "image": "",
      "mainImageUrl": "",
      "view360Url": "",
      "facilities": ["Wi-Fi", "화이트보드"],
      "description": "자유로운 아이디어 회의 공간",
      "building": "3기술관",
      "floor": "1층",
      "createdAt": FieldValue.serverTimestamp(),
    },

    // ========== 5기술관 - 1층 ==========
    {
      "name": "개인미디어실",
      "location": "5기술관 1층",
      "capacity": 10,
      "image": "",
      "mainImageUrl": "",
      "view360Url": "",
      "facilities": ["Wi-Fi", "스크린", "에어컨", "콘센트"],
      "description": "개인 미디어 제작 공간",
      "building": "5기술관",
      "floor": "1층",
      "createdAt": FieldValue.serverTimestamp(),
    },
    {
      "name": "세미나실",
      "location": "5기술관 1층",
      "capacity": 30,
      "image": "",
      "mainImageUrl": "",
      "view360Url": "",
      "facilities": ["Wi-Fi", "스크린", "에어컨", "화이트보드"],
      "description": "세미나 및 발표 전용 공간",
      "building": "5기술관",
      "floor": "1층",
      "createdAt": FieldValue.serverTimestamp(),
    },
    {
      "name": "미디어편집실",
      "location": "5기술관 1층",
      "capacity": 20,
      "image": "",
      "mainImageUrl": "",
      "view360Url": "",
      "facilities": ["Wi-Fi", "스크린", "에어컨", "콘센트"],
      "description": "미디어 편집 전용 강의실",
      "building": "5기술관",
      "floor": "1층",
      "createdAt": FieldValue.serverTimestamp(),
    },
    {
      "name": "AR그래픽실",
      "location": "5기술관 1층",
      "capacity": 25,
      "image": "",
      "mainImageUrl": "",
      "view360Url": "",
      "facilities": ["Wi-Fi", "스크린", "에어컨", "콘센트"],
      "description": "AR 그래픽 실습 전용 강의실",
      "building": "5기술관",
      "floor": "1층",
      "createdAt": FieldValue.serverTimestamp(),
    },
    {
      "name": "실감형콘텐츠운영실습실",
      "location": "5기술관 1층",
      "capacity": 25,
      "image": "",
      "mainImageUrl": "",
      "view360Url": "",
      "facilities": ["Wi-Fi", "스크린", "에어컨", "콘센트"],
      "description": "실감형 콘텐츠 운영 실습 강의실",
      "building": "5기술관",
      "floor": "1층",
      "createdAt": FieldValue.serverTimestamp(),
    },

    // ========== 5기술관 - 2층 ==========
    {
      "name": "AI융합프로젝트실습실",
      "location": "5기술관 2층",
      "capacity": 30,
      "image": "",
      "mainImageUrl": "",
      "view360Url": "",
      "facilities": ["Wi-Fi", "스크린", "에어컨", "콘센트"],
      "description": "AI 융합 프로젝트 실습 강의실",
      "building": "5기술관",
      "floor": "2층",
      "createdAt": FieldValue.serverTimestamp(),
    },
    {
      "name": "인공지능프로그래밍실습실",
      "location": "5기술관 2층",
      "capacity": 30,
      "image": "",
      "mainImageUrl": "",
      "view360Url": "",
      "facilities": ["Wi-Fi", "스크린", "에어컨", "콘센트"],
      "description": "인공지능 프로그래밍 실습 강의실",
      "building": "5기술관",
      "floor": "2층",
      "createdAt": FieldValue.serverTimestamp(),
    },
    {
      "name": "IoT제어실습실",
      "location": "5기술관 2층",
      "capacity": 30,
      "image": "",
      "mainImageUrl": "",
      "view360Url": "",
      "facilities": ["Wi-Fi", "스크린", "에어컨", "콘센트"],
      "description": "IoT 제어 실습 강의실",
      "building": "5기술관",
      "floor": "2층",
      "createdAt": FieldValue.serverTimestamp(),
    },

    // ========== 5기술관 - 3층 ==========
    {
      "name": "강의실",
      "location": "5기술관 3층",
      "capacity": 40,
      "image": "",
      "mainImageUrl": "",
      "view360Url": "",
      "facilities": ["Wi-Fi", "스크린", "에어컨"],
      "description": "일반 강의실",
      "building": "5기술관",
      "floor": "3층",
      "createdAt": FieldValue.serverTimestamp(),
    },
    {
      "name": "스터디룸",
      "location": "5기술관 3층",
      "capacity": 10,
      "image": "",
      "mainImageUrl": "",
      "view360Url": "",
      "facilities": ["Wi-Fi", "화이트보드"],
      "description": "소규모 스터디 공간",
      "building": "5기술관",
      "floor": "3층",
      "createdAt": FieldValue.serverTimestamp(),
    },
    {
      "name": "반도체제어실",
      "location": "5기술관 3층",
      "capacity": 30,
      "image": "",
      "mainImageUrl": "",
      "view360Url": "",
      "facilities": ["Wi-Fi", "스크린", "에어컨", "콘센트"],
      "description": "반도체 제어 실습 강의실",
      "building": "5기술관",
      "floor": "3층",
      "createdAt": FieldValue.serverTimestamp(),
    },
    {
      "name": "전자CAD실",
      "location": "5기술관 3층",
      "capacity": 30,
      "image": "",
      "mainImageUrl": "",
      "view360Url": "",
      "facilities": ["Wi-Fi", "스크린", "에어컨", "콘센트"],
      "description": "전자 CAD 실습 강의실",
      "building": "5기술관",
      "floor": "3층",
      "createdAt": FieldValue.serverTimestamp(),
    },
    {
      "name": "기초전자실습실",
      "location": "5기술관 3층",
      "capacity": 30,
      "image": "",
      "mainImageUrl": "",
      "view360Url": "",
      "facilities": ["Wi-Fi", "스크린", "에어컨", "콘센트"],
      "description": "기초 전자 실습 강의실",
      "building": "5기술관",
      "floor": "3층",
      "createdAt": FieldValue.serverTimestamp(),
    },

    // ========== 5기술관 - 4층 ==========
    {
      "name": "시제품창의개발실",
      "location": "5기술관 4층",
      "capacity": 25,
      "image": "",
      "mainImageUrl": "",
      "view360Url": "",
      "facilities": ["Wi-Fi", "스크린", "에어컨", "콘센트"],
      "description": "시제품 창의 개발 실습 공간",
      "building": "5기술관",
      "floor": "4층",
      "createdAt": FieldValue.serverTimestamp(),
    },
    {
      "name": "아이디어카페",
      "location": "5기술관 4층",
      "capacity": 15,
      "image": "",
      "mainImageUrl": "",
      "view360Url": "",
      "facilities": ["Wi-Fi", "화이트보드"],
      "description": "자유로운 아이디어 회의 카페",
      "building": "5기술관",
      "floor": "4층",
      "createdAt": FieldValue.serverTimestamp(),
    },
    {
      "name": "디자인워크샵실습실",
      "location": "5기술관 4층",
      "capacity": 25,
      "image": "",
      "mainImageUrl": "",
      "view360Url": "",
      "facilities": ["Wi-Fi", "스크린", "에어컨", "콘센트"],
      "description": "디자인 워크샵 실습 강의실",
      "building": "5기술관",
      "floor": "4층",
      "createdAt": FieldValue.serverTimestamp(),
    },
    {
      "name": "융합디자인실습실",
      "location": "5기술관 4층",
      "capacity": 25,
      "image": "",
      "mainImageUrl": "",
      "view360Url": "",
      "facilities": ["Wi-Fi", "스크린", "에어컨", "콘센트"],
      "description": "융합 디자인 실습 강의실",
      "building": "5기술관",
      "floor": "4층",
      "createdAt": FieldValue.serverTimestamp(),
    },
    {
      "name": "디지털디자인실습실",
      "location": "5기술관 4층",
      "capacity": 25,
      "image": "",
      "mainImageUrl": "",
      "view360Url": "",
      "facilities": ["Wi-Fi", "스크린", "에어컨", "콘센트"],
      "description": "디지털 디자인 실습 강의실",
      "building": "5기술관",
      "floor": "4층",
      "createdAt": FieldValue.serverTimestamp(),
    },
    {
      "name": "미디어창작실습실",
      "location": "5기술관 4층",
      "capacity": 25,
      "image": "",
      "mainImageUrl": "",
      "view360Url": "",
      "facilities": ["Wi-Fi", "스크린", "에어컨", "콘센트"],
      "description": "미디어 창작 실습 강의실",
      "building": "5기술관",
      "floor": "4층",
      "createdAt": FieldValue.serverTimestamp(),
    },

    // ========== 7기술관 - 3층 ==========
    {
      "name": "소그룹실",
      "location": "7기술관 3층",
      "capacity": 10,
      "image": "",
      "mainImageUrl": "",
      "view360Url": "",
      "facilities": ["Wi-Fi", "화이트보드"],
      "description": "소규모 그룹 활동 공간",
      "building": "7기술관",
      "floor": "3층",
      "createdAt": FieldValue.serverTimestamp(),
    },
    {
      "name": "강의실",
      "location": "7기술관 3층",
      "capacity": 40,
      "image": "",
      "mainImageUrl": "",
      "view360Url": "",
      "facilities": ["Wi-Fi", "스크린", "에어컨"],
      "description": "일반 강의실",
      "building": "7기술관",
      "floor": "3층",
      "createdAt": FieldValue.serverTimestamp(),
    },
    {
      "name": "반도체 시스템 제작실",
      "location": "7기술관 3층",
      "capacity": 30,
      "image": "",
      "mainImageUrl": "",
      "view360Url": "",
      "facilities": ["Wi-Fi", "스크린", "에어컨", "콘센트"],
      "description": "반도체 시스템 제작 실습 강의실",
      "building": "7기술관",
      "floor": "3층",
      "createdAt": FieldValue.serverTimestamp(),
    },
  ];

  // 일괄 추가
  final batch = firestore.batch();

  for (var spaceData in spacesData) {
    final docRef = firestore.collection('spaces').doc();
    batch.set(docRef, spaceData);
  }

  await batch.commit();
  print('✅ ${spacesData.length}개의 공간 데이터가 추가되었습니다!');
}

// 기존 데이터 전체 삭제 (주의!)
Future<void> deleteAllSpaces() async {
  final firestore = FirebaseFirestore.instance;
  final snapshot = await firestore.collection('spaces').get();

  final batch = firestore.batch();
  for (var doc in snapshot.docs) {
    batch.delete(doc.reference);
  }

  await batch.commit();
  print('🗑️ ${snapshot.docs.length}개의 공간 데이터가 삭제되었습니다!');
}
